import type { Discount } from "./types"

export const discounts: Discount[] = [
  {
    id: "1",
    brand: "Nike",
    type: "Coupon",
    code: "SUMMER25",
    expiryDate: "2025-08-31",
    description: "25% off summer collection",
    url: "https://nike.com",
    logo: "/placeholder.svg?height=64&width=64&text=Nike",
    category: "Fashion",
    isPublic: true,
    copiedCount: 12,
    lastCopied: "2025-05-10T14:30:00Z",
  },
  {
    id: "2",
    brand: "Amazon",
    type: "Deal",
    code: "PRIME15",
    expiryDate: "2025-07-15",
    description: "$15 off orders over $50",
    url: "https://amazon.com",
    logo: "/placeholder.svg?height=64&width=64&text=Amazon",
    category: "Shopping",
    isPublic: false,
    copiedCount: 5,
    lastCopied: "2025-05-08T09:15:00Z",
  },
  {
    id: "3",
    brand: "Uber Eats",
    type: "Coupon",
    code: "EATS10",
    expiryDate: "2025-06-30",
    description: "$10 off your first order",
    url: "https://ubereats.com",
    logo: "/placeholder.svg?height=64&width=64&text=Uber",
    category: "Food & Dining",
    isPublic: true,
    copiedCount: 8,
    lastCopied: "2025-05-09T18:45:00Z",
  },
  {
    id: "4",
    brand: "Spotify",
    type: "Deal",
    code: "PREMIUM3",
    expiryDate: "2025-05-15",
    description: "3 months of Premium for $0.99",
    url: "https://spotify.com",
    logo: "/placeholder.svg?height=64&width=64&text=Spotify",
    category: "Entertainment",
    isPublic: true,
    copiedCount: 20,
    lastCopied: "2025-05-11T10:20:00Z",
  },
  {
    id: "5",
    brand: "Airbnb",
    type: "Referral",
    code: "TRAVEL50",
    expiryDate: "2025-12-31",
    description: "$50 credit for new users",
    url: "https://airbnb.com",
    logo: "/placeholder.svg?height=64&width=64&text=Airbnb",
    category: "Travel",
    isPublic: false,
    copiedCount: 3,
    lastCopied: "2025-05-05T12:10:00Z",
  },
  {
    id: "6",
    brand: "Sephora",
    type: "Cashback",
    code: "BEAUTY20",
    expiryDate: "2025-06-01",
    description: "20% cashback on all purchases",
    url: "https://sephora.com",
    logo: "/placeholder.svg?height=64&width=64&text=Sephora",
    category: "Health & Beauty",
    isPublic: true,
    copiedCount: 15,
    lastCopied: "2025-05-10T16:55:00Z",
  },
]

export const categories: string[] = [
  "Food & Dining",
  "Shopping",
  "Travel",
  "Entertainment",
  "Electronics",
  "Fashion",
  "Health & Beauty",
  "Home & Garden",
  "Other",
]

